set encoding=utf-8

"背景颜色
set background=dark

"文件编码
set fileencodings=utf-8,gbk,utf-16le,cp1252,iso-8859-15,ucs-bom

"高亮指定列
set colorcolumn=100,120

"高度当前列
set cursorcolumn

"高亮当前行
set cursorline

"主题配色
colorscheme solarized
"colorscheme molokai

"关闭vi兼容模式
set nocompatible

"indent: 允许删除自动缩进的内容
"eol: 允许删除换行符
"start: 允许删除进入插入模式前已有的内容
set backspace=indent,eol,start

"状态栏显示，0: never, 1: multi windows, 2: always
set laststatus=2

"光标距离顶部、底部最小行数
set scrolloff=3

"底部的行号等显示
set ruler

"Tab宽度
set tabstop=4

"缩进宽度
set shiftwidth=4

"编辑时可以将tab替换为空格
set expandtab

"自动缩进
set cindent

"关闭错误信息响铃
set noerrorbells

"显示行号
set number

"高亮查询
set hlsearch

"自动保存
set autowrite

"自动切换当前目录为当前文件所在的目录
"set autochdir

"代码折叠模式
"set foldmethod=manual

"windows之前的填充符号
set fillchars=vert:\|

"插入匹配括号
set showmatch

"GUI字体
set guifont=YaHei\Consolas\Hybrid\12

"语法高亮
syntax enable

"语法高亮默认颜色配置 hi-normal
syntax on

"下一个buffer
nnoremap <leader>bn :bnext<CR>
"上一个buffer
nnoremap <leader>bp :bprevious<CR>
"删除buffer
nnoremap <leader>bd :bdelete<CR>
"列出所有buffers
nnoremap <leader>bl :buffers<CR>

"============== Plugins List ==================================================
call plug#begin('~/.vim/plugged')
"golang
Plug 'fatih/vim-go', { 'do': ':GoInstallBinaries' }

"代码补全
Plug 'ycm-core/YouCompleteMe'

"python 代码格式化
Plug 'tell-k/vim-autopep8'

"括号、引号补全
Plug 'jiangmiao/auto-pairs'

"语法检查
Plug 'vim-syntastic/syntastic'

"快速注释
Plug 'preservim/nerdcommenter'

"状态栏
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

"c++代码格式化
Plug 'rhysd/vim-clang-format'

"目录树
Plug 'scrooloose/nerdtree'

"快速查找文件
Plug 'kien/ctrlp.vim'

"Copilot
Plug 'github/copilot.vim'

call plug#end()

"=============== Plugin Config 'scrooloose/nerdtree' ==========================
"按下F2 调出/隐藏
nnoremap <silent> <F2> :execute 'NERDTreeToggle ' . getcwd()<CR>

let NERDTreeChDirMode=1
let NERDTreeShowBookmarks=1
let NERDTreeWinSize=30
let NERDTreeShowHidden=1
let NERDTreeIgnore=['\~$', '\.pyc$', '\.swp$', '\.git$']

"=============== Plugin Config 'tell-k/vim-autopep8' ==========================
autocmd FileType python noremap <buffer> <F8> :call Autopep8()<CR>
let g:autopep8_global_config="${HOME}/.config/flake8"
"autocmd BufWritePost *.py call Flake8()

"=============== Plugin Config 'kien/ctrlp.vim' ===============================
"Ctrl+p 快速搜索

"=============== Plugin Config 'vim-syntastic/syntastic' ======================
map <F5> :SyntasticToggleMode<CR> :SyntasticCheck<CR>
let g:syntastic_python_python_exe="~/.local/bin/python"
let g:syntastic_python_checkers=['flake8']
let g:syntastic_python_flake8_args='--config=${HOME}/.config/flake8'
let g:syntastic_always_populate_loc_list=0
let g:syntastic_auto_loc_list=1
"文件打开的时候执行语法校验
let g:syntastic_check_on_open=0
"保存退出的时候执行语法校验
let g:syntastic_check_on_wq=1

set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

"=============== Plugin Config 'Valloric/YouCompleteMe' =======================
"YouCompleteMe 功能
let g:ycm_global_ycm_extra_conf="~/.ycm_extra_conf.py"
"ycm使用的python路径
let g:ycm_python_binary_path="~/.local/bin/python"
"补全功能在注释中同样有效
let g:ycm_complete_in_comments=1
"允许 vim 加载 .ycm_extra_conf.py 文件，不再提示
let g:ycm_confirm_extra_conf=0
"开启 YCM 基于标签引擎
let g:ycm_collect_identifiers_from_tags_files=1
"补全内容不以分割子窗口形式出现，只显示补全列表
"set completeopt-=preview
"从第一个键入字符就开始罗列匹配项
let g:ycm_min_num_of_chars_for_completion=1
"禁止缓存匹配项，每次都重新生成匹配项
let g:ycm_cache_omnifunc=0
"语法关键字补全
let g:ycm_seed_identifiers_with_syntax=1
"开启语义补全
let g:ycm_seed_identifiers_with_syntax=1
"autocmd InsertLeave * if pumvisible() == 0|pclose|endif
"let g:ycm_autoclose_preview_window_after_insertion=1
let g:ycm_autoclose_preview_window_after_completion=1
let g:ycm_collect_identifiers_from_comments_and_strings=1

"GoTo 跳转
let g:ycm_goto_buffer_command = 'split-or-existing-window'
nnoremap <leader>gl :tab YcmCompleter GoToDeclaration<CR>
nnoremap <leader>gf :tab YcmCompleter GoToDefinition<CR>
nnoremap <leader>gd :tab YcmCompleter GoToDefinitionElseDeclaration<CR>

"=============== Plugin Config 'vim-airline/vim-airline' ======================
let g:airline_theme='solarized'
let g:airline#extensions#tabline#enabled=1
let g:airline#extensions#tabline#left_sep=' '
let g:airline#extensions#tabline#left_alt_sep='|'

"=============== File End =====================================================
